{{- if .Values.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: ngcloud-api-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.apiToken | quote }}
{{- end }}
